// Fetch ArchiMate element icons from the Archi tool repository (MIT) and
// generate src/convert/archimate-icons.mjs with base64 data URLs.
// Run: node scripts/build-icons.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BASE = 'https://raw.githubusercontent.com/archimatetool/archi/master/com.archimatetool.editor/img/archimate';

// layer.element -> Archi icon filename (without .png)
const MAP = {
  'business.actor': 'business-actor', 'business.role': 'business-role',
  'business.collaboration': 'business-collaboration', 'business.interface': 'business-interface',
  'business.process': 'business-process', 'business.function': 'business-function',
  'business.interaction': 'business-interaction', 'business.event': 'business-event',
  'business.service': 'business-service', 'business.object': 'business-object',
  'business.contract': 'contract', 'business.representation': 'representation',
  'business.product': 'product',
  'application.component': 'application-component', 'application.collaboration': 'application-collaboration',
  'application.interface': 'application-interface', 'application.function': 'application-function',
  'application.interaction': 'application-interaction', 'application.process': 'application-process',
  'application.event': 'application-event', 'application.service': 'application-service',
  'application.dataobject': 'data-object',
  'technology.node': 'node', 'technology.device': 'device',
  'technology.systemsoftware': 'system-software', 'technology.collaboration': 'technology-collaboration',
  'technology.interface': 'technology-interface', 'technology.path': 'path',
  'technology.communicationnetwork': 'communication-network', 'technology.function': 'technology-function',
  'technology.process': 'technology-process', 'technology.interaction': 'technology-interaction',
  'technology.event': 'technology-event', 'technology.service': 'technology-service',
  'technology.artifact': 'artifact',
  'motivation.stakeholder': 'stakeholder', 'motivation.driver': 'driver',
  'motivation.assessment': 'assessment', 'motivation.goal': 'goal',
  'motivation.outcome': 'outcome', 'motivation.principle': 'principle',
  'motivation.requirement': 'requirement', 'motivation.constraint': 'constraint',
  'motivation.value': 'value', 'motivation.meaning': 'meaning',
  'strategy.resource': 'resource', 'strategy.capability': 'capability',
  'strategy.courseofaction': 'course-of-action', 'strategy.valuestream': 'value-stream',
  'physical.equipment': 'equipment', 'physical.facility': 'facility',
  'physical.distributionnetwork': 'distribution-network', 'physical.material': 'material',
};

const entries = [];
let failed = 0;
for (const [key, file] of Object.entries(MAP)) {
  const res = await fetch(`${BASE}/${file}.png`);
  if (!res.ok) {
    console.error(`FAIL ${key} <- ${file}.png: HTTP ${res.status}`);
    failed += 1;
    continue;
  }
  const buf = Buffer.from(await res.arrayBuffer());
  entries.push(`  '${key}': 'data:image/png;base64,${buf.toString('base64')}',`);
}

const out = `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Icons: Archi tool (https://github.com/archimatetool/archi), MIT License.
// Key: '<layer>.<element>' (Triton 2 ArchiMate notation), value: PNG data URL.
export const ARCHIMATE_ICONS = {
${entries.join('\n')}
};

export function archimateIconDataUrl(layer, element) {
  return ARCHIMATE_ICONS[\`\${layer}.\${element}\`] || null;
}
`;

fs.writeFileSync(path.join(root, 'src', 'convert', 'archimate-icons.mjs'), out, 'utf8');
console.log(`written ${entries.length} icons, ${failed} failed`);
process.exit(failed ? 1 : 0);
